# Generated by Django 3.0.3 on 2020-02-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
